//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyCollection.Model.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyCollection.Model.Resources.ExceptionMessages", typeof(ExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string ERROR1000 {
            get {
                return ResourceManager.GetString("ERROR1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter valid credentials.
        /// </summary>
        public static string ERROR10000 {
            get {
                return ResourceManager.GetString("ERROR10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter valid user name.
        /// </summary>
        public static string ERROR10001 {
            get {
                return ResourceManager.GetString("ERROR10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User token is expired or invalid.
        /// </summary>
        public static string ERROR10002 {
            get {
                return ResourceManager.GetString("ERROR10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while saving data into database.
        /// </summary>
        public static string ERROR10003 {
            get {
                return ResourceManager.GetString("ERROR10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User is inactive.
        /// </summary>
        public static string ERROR10004 {
            get {
                return ResourceManager.GetString("ERROR10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Some error occurred while processing your request. Please try after some time..
        /// </summary>
        public static string ERROR50000 {
            get {
                return ResourceManager.GetString("ERROR50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please choose a new password because your temporary password is expired.
        /// </summary>
        public static string ERROR5001 {
            get {
                return ResourceManager.GetString("ERROR5001", resourceCulture);
            }
        }
    }
}
