//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyCollection.Model.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MasterData() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyCollection.Model.Resources.MasterData", typeof(MasterData).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to GetApplicationToken.
        /// </summary>
        public static string GetApplicationToken {
            get {
                return ResourceManager.GetString("GetApplicationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AppSettingsList_Get.
        /// </summary>
        public static string GetAppSettingsList {
            get {
                return ResourceManager.GetString("GetAppSettingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AppSettingValue_Get.
        /// </summary>
        public static string GetAppSettingValue {
            get {
                return ResourceManager.GetString("GetAppSettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to GetGroupPayItemListItems.
        /// </summary>
        public static string GetGroupPayItemListItems {
            get {
                return ResourceManager.GetString("GetGroupPayItemListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to GetEmailTemplateListItems.
        /// </summary>
        public static string GetEmailTemplateListItems {
            get {
                return ResourceManager.GetString("GetEmailTemplateListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to GetListItems.
        /// </summary>
        public static string GetListItems {
            get {
                return ResourceManager.GetString("GetListItems", resourceCulture);
            }
        }
    }
}
